Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "kaas"
    config.vm.network :public_network
    config.vm.provider "virtualbox" do |vb|
        vb.memory="8196"
        vb.cpus = 4
        vb.name = "kaas"
    end
end