Vagrant.configure("2") do |config|
    config.vm.box = "fedora/37-cloud-base"
    config.vm.box_version = "37.20221105.0"
    config.vm.hostname = "kaas"
    config.vm.network :public_network
    config.vm.provider "virtualbox" do |vb|
        config.vm.synced_folder "../../../ansible", "/ansible", :mount_options => ["dmode=700", "fmode=700"]
        config.vm.provision "ansible_local" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.limit = "all"
            ansible.config_file = "../../../ansible/ansible.cfg"
            ansible.become = true
            ansible.playbook = "../../../ansible/site.yml"
            ansible.inventory_path = "../../../ansible/hosts" 
        end
        vb.memory="8196"
        vb.cpus = 4 
        vb.name = "kaas"
    end
end